---
development:
  cloud_name: frozen-gorge
  api_key: '479786358336727'
  api_secret: KWn1XwAJ-CmI0GoAA8etrQ6AKbk
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: frozen-gorge
  api_key: '479786358336727'
  api_secret: KWn1XwAJ-CmI0GoAA8etrQ6AKbk
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: frozen-gorge
  api_key: '479786358336727'
  api_secret: KWn1XwAJ-CmI0GoAA8etrQ6AKbk
  enhance_image_tag: true
  static_file_support: false
